// ------------------------------------------------------------------------------
// <auto-generated>
// Este código se generó a partir de una plantilla.
// 
// Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
// Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualBasic;

public partial class Cronograma
{
    public int idCronograma { get; set; }
    public Nullable<int> nrocuota { get; set; }
    public string tipo { get; set; }
    public Nullable<DateTime> fechaoperacion { get; set; }
    public Nullable<DateTime> fechaPago { get; set; }
    public string cuenta { get; set; }
    public string descripcion { get; set; }
    public string glosa { get; set; }
    public Nullable<int> identidad { get; set; }
    public Nullable<int> idDocumentoRef { get; set; }
    public Nullable<int> idDocumentoDetalleRef { get; set; }
    public Nullable<int> idDocumentoPago { get; set; }
    public string moneda { get; set; }
    public Nullable<decimal> tipocambio { get; set; }
    public Nullable<decimal> montoAutorizadoMN { get; set; }
    public Nullable<decimal> montoAutorizadoME { get; set; }
    public Nullable<int> usuarioResponssable { get; set; }
    public string usuarioActualizacion { get; set; }
    public Nullable<DateTime> fechaActualizacion { get; set; }
    public string tipoRazon { get; set; }
    public string autorizacion { get; set; }
    public string fechaContable { get; set; }
    public string estado { get; set; }

   // public virtual documento documento { get; set; }
}
