// ------------------------------------------------------------------------------
// <auto-generated>
// Este código se generó a partir de una plantilla.
// 
// Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
// Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualBasic;

public partial class documentoventaAbarrotes
{
    public int idDocumento { get; set; }
    public string tipoOperacion { get; set; }
    public string codigoLibro { get; set; }
    public string idEmpresa { get; set; }
    public int idEstablecimiento { get; set; }
    public string tipoDocumento { get; set; }
    public Nullable<DateTime> fechaLaboral { get; set; }
    public Nullable<DateTime> fechaDoc { get; set; }
    public Nullable<DateTime> fechaVcto { get; set; }
    public string horaVenta { get; set; }
    public Nullable<DateTime> fechaConfirmacion { get; set; }
    public string fechaPeriodo { get; set; }
    public string serie { get; set; }
    public int numeroDoc { get; set; }
    public string numeroDocNormal { get; set; }
    public string serieVenta { get; set; }
    public Nullable<int> numeroVenta { get; set; }
    public Nullable<int> idClientePedido { get; set; }
    public string nombrePedido { get; set; }
    public Nullable<int> idCliente { get; set; }
    public string moneda { get; set; }
    public Nullable<decimal> tipoCambio { get; set; }
    public Nullable<decimal> tasaIgv { get; set; }
    public Nullable<decimal> bi01 { get; set; }
    public Nullable<decimal> bi02 { get; set; }
    public Nullable<decimal> isc01 { get; set; }
    public Nullable<decimal> isc02 { get; set; }
    public Nullable<decimal> igv01 { get; set; }
    public Nullable<decimal> igv02 { get; set; }
    public Nullable<decimal> otc01 { get; set; }
    public Nullable<decimal> otc02 { get; set; }
    public Nullable<decimal> bi01us { get; set; }
    public Nullable<decimal> bi02us { get; set; }
    public Nullable<decimal> isc01us { get; set; }
    public Nullable<decimal> isc02us { get; set; }
    public Nullable<decimal> igv01us { get; set; }
    public Nullable<decimal> igv02us { get; set; }
    public Nullable<decimal> otc01us { get; set; }
    public Nullable<decimal> otc02us { get; set; }
    public Nullable<decimal> ImporteNacional { get; set; }
    public Nullable<decimal> ImporteExtranjero { get; set; }
    public Nullable<decimal> importeCostoMN { get; set; }
    public Nullable<decimal> importeCostoME { get; set; }
    public string estadoCobro { get; set; }
    public Nullable<int> establecimientoCobro { get; set; }
    public string entidadFinanciera { get; set; }
    public string glosa { get; set; }
    public string terminos { get; set; }
    public string notaCredito { get; set; }
    public string tipoVenta { get; set; }
    public string tipoVentaNeg { get; set; }
    public string modulo { get; set; }
    public string idPadre { get; set; }
    public string notificacionAsiento { get; set; }
    public string estado { get; set; }
    public string estadoEntrega { get; set; }
    public Nullable<int> nroImpresion { get; set; }
    public string EnvioSunat { get; set; }
    public string ticketElectronico { get; set; }
    public Nullable<long> numeracionElectronica { get; set; }
    public string nroGuia { get; set; }
    public string nroOrdenVenta { get; set; }
    public Nullable<decimal> icbper { get; set; }
    public Nullable<decimal> icbperus { get; set; }
    public string descripcionVenta { get; set; }
    public string usuarioActualizacion { get; set; }
    public Nullable<DateTime> fechaActualizacion { get; set; }
    public string tienda { get; set; }
    public Nullable<int> idEstablecimientoVenta { get; set; }
    public Nullable<int> IdUserBox { get; set; }
    public Nullable<int> idAlmacenVenta { get; set; }
    public string motivoAnulacion { get; set; }
    public Nullable<DateTime> fechaAnulacion { get; set; }
    public string UserSpk { get; set; }
    public Nullable<DateTime> fechaEnvioSunat { get; set; }
    public Nullable<DateTime> fechaComunicacionBajaSunat { get; set; }
    public Nullable<int> idEnvio { get; set; }
    public Nullable<int> idBaja { get; set; }
    public Nullable<int> idDistribucion { get; set; }
    public Nullable<decimal> tasaRc { get; set; }
    public Nullable<bool> consumoTotal { get; set; }

    //public virtual documento documento { get; set; }
    //public virtual List<documentoAnticipoConciliacion> documentoAnticipoConciliacion { get; set; } = new HashSet<documentoAnticipoConciliacion>().ToList();
    public virtual List<documentoventaAbarrotesDet> documentoventaAbarrotesDet { get; set; } = new HashSet<documentoventaAbarrotesDet>().ToList();
    //public virtual orderInformation orderInformation { get; set; }
    //public virtual List<ventaDetalle_oferta> ventaDetalle_oferta { get; set; } = new HashSet<ventaDetalle_oferta>().ToList();
}
