// ------------------------------------------------------------------------------
// <auto-generated>
// Este código se generó a partir de una plantilla.
// 
// Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
// Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualBasic;

public partial class documentoventaAbarrotesDet
{
    public int idDocumento { get; set; }
    public int secuencia { get; set; }
    public Nullable<int> idAlmacenOrigen { get; set; }
    public Nullable<int> establecimientoOrigen { get; set; }
    public string empresaOrigen { get; set; }
    public string cuentaOrigen { get; set; }
    public string idItem { get; set; }
    public string nombreItem { get; set; }
    public Nullable<DateTime> fechaVcto { get; set; }
    public string tipoExistencia { get; set; }
    public string destino { get; set; }
    public Nullable<int> equivalencia_id { get; set; }
    public Nullable<int> catalogo_id { get; set; }
    public Nullable<int> idVariante { get; set; }
    public string variantName { get; set; }
    public string unidad2 { get; set; }
    public string unidad1 { get; set; }
    public Nullable<decimal> monto1 { get; set; }
    public string monto2 { get; set; }
    public Nullable<decimal> precioUnitario { get; set; }
    public Nullable<decimal> precioUnitarioUS { get; set; }
    public Nullable<decimal> importeMN { get; set; }
    public Nullable<decimal> importeME { get; set; }
    public Nullable<decimal> importeMNK { get; set; }
    public Nullable<decimal> importeMEK { get; set; }
    public Nullable<decimal> descuentoMN { get; set; }
    public Nullable<decimal> descuentoME { get; set; }
    public Nullable<decimal> descuentoGrupoMN { get; set; }
    public Nullable<decimal> descuentoGrupoME { get; set; }
    public Nullable<decimal> montokardex { get; set; }
    public Nullable<decimal> montoIsc { get; set; }
    public Nullable<decimal> montoIgv { get; set; }
    public Nullable<decimal> otrosTributos { get; set; }
    public Nullable<decimal> montokardexUS { get; set; }
    public Nullable<decimal> montoIscUS { get; set; }
    public Nullable<decimal> montoIgvUS { get; set; }
    public Nullable<decimal> otrosTributosUS { get; set; }
    public Nullable<decimal> salidaCostoMN { get; set; }
    public Nullable<decimal> salidaCostoME { get; set; }
    public Nullable<decimal> cantidadCredito { get; set; }
    public Nullable<decimal> cantidadDebito { get; set; }
    public Nullable<decimal> notaCreditoMN { get; set; }
    public Nullable<decimal> notaCreditoME { get; set; }
    public Nullable<decimal> notaDebitoMN { get; set; }
    public Nullable<decimal> notaDebitoME { get; set; }
    public string preEvento { get; set; }
    public Nullable<int> idPadreDTVenta { get; set; }
    public string estadoMovimiento { get; set; }
    public string tipoVenta { get; set; }
    public string entregado { get; set; }
    public string estadoPago { get; set; }
    public Nullable<int> categoria { get; set; }
    public string estadoEntrega { get; set; }
    public Nullable<int> idCajaUsuario { get; set; }
    public Nullable<int> codigoLote { get; set; }
    public Nullable<int> idbeneficio { get; set; }
    public string tipobeneficio { get; set; }
    public Nullable<decimal> beneficiobase { get; set; }
    public Nullable<bool> bonificacion { get; set; }
    public Nullable<decimal> montoIcbper { get; set; }
    public Nullable<decimal> montoIcbperUS { get; set; }
    public Nullable<decimal> tasaIcbper { get; set; }
    public string detalleAdicional { get; set; }
    public Nullable<int> idDistribucion { get; set; }
    public string estadoDistribucion { get; set; }
    public Nullable<int> idPadre { get; set; }
    public string usuarioModificacion { get; set; }
    public Nullable<DateTime> fechaModificacion { get; set; }
    public Nullable<int> idLote { get; set; }
    public Nullable<int> idLoteDetalle { get; set; }
    public Nullable<bool> controlInvt { get; set; }
    public Nullable<bool> delivery { get; set; }
    public Nullable<int> idAlmacenDestino { get; set; }
    public string empresaDestino { get; set; }
    public Nullable<int> establecimientoDestino { get; set; }
    public string stateKitchen { get; set; }
    public string stateDeliveryTable { get; set; }
    public string messageKitchen { get; set; }
    public string placeRest { get; set; }
    public Nullable<int> idplaceRest { get; set; }
    public Nullable<int> timePreparation { get; set; }
    public Nullable<DateTime> timePlateFinish { get; set; }
    public Nullable<int> idUserOrder { get; set; }    
    public virtual documentoventaAbarrotes documentoventaAbarrotes { get; set; }    
}
